version: '3.8'

services:

  sym_database:
    container_name: sym_database
    image: mariadb:10.3.34
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: snubes
      MYSQL_USER: snubes
      MYSQL_PASSWORD: snubes
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - sym_skeleton_network
      
  sym_php:
    container_name: sym_php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_docker
    depends_on:
      - sym_database
    networks:
      - sym_skeleton_network
      
  sym_nginx:
    container_name: sym_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - sym_php
      - sym_database
    networks:
      - sym_skeleton_network

networks:
  sym_skeleton_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.167.0.0/16