controllers:
    resource: ../src/Context/DonnerKebab/Infrastructure/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

post_Donner:
    path: /api/donner
    controller: App\Context\DonnerKebab\Infrastructure\Controller\DonnerKebabPostEndpoint::postDonnerKebab

get_Donner:
    path: /api/donner/{id}
    controller: App\Context\DonnerKebab\Infrastructure\Controller\DonnerKebabGetEndpoint::getDonnerKebab