controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

post_doner:
    path: /api/doner
    controller: App\DonerKebab\Infrastructure\Controller\DonerKebabPostEndpoint::postDonerKebab

get_doner:
    path: /api/doner/{id}
    controller: App\DonerKebab\Infrastructure\Controller\DonerKebabGetEndpoint::getDonerKebab