controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

post_Donner:
    path: /api/donner
    controller: App\DonnerKebab\Infrastructure\Controller\DonnerKebabPostEndpoint::postDonnerKebab

get_Donner:
    path: /api/donner/{id}
    controller: App\DonnerKebab\Infrastructure\Controller\DonnerKebabGetEndpoint::getDonnerKebab